feat: inference_fn changed from asynchronous to synchronous
bioinformatist/cml pull request #7
Opened 2023-07-21 10:05 UTC by lazyky

- fix bugs
- complete function test
- delete the directory parameter in TaskConfig

Resove #1

2023-07-22 06:18 UTC, bioinformatist requested changes

2023-07-22 06:18 UTC, bioinformatist commented on cml-core/src/core/inference.rs
> +    async fn inference<FN>(
I think here we need a parameter `available_status`, just like `working_status` in `task.rs`, which allows user to custom the list of available status. For example, one could mark some status for a specific type of inference, but use others for another inference operation.

2023-07-22 06:18 UTC, bioinformatist commented on cml-tdengine/src/core/inference.rs
> +            .query_one(format!("SELECT LAST(ts) FROM task.`{}`", metadata.batch()))
Here we need to pick the task according to `available_status`.

BTW, `query_one` is a new API which is a better option for these scenarios. Could you replace the original code with it in other appropriate places?

2023-07-22 06:22 UTC, bioinformatist commented on cml-core/src/core/inference.rs
> +    async fn inference<FN>(
I think here we need a parameter available_status, just like working_status in task.rs, which allows user to custom the list of available status. For example, one could mark some status for a specific type of inference, but use others for another inference operation.

2023-07-22 06:25 UTC, bioinformatist requested changes
The design of the trait method `inference` should be improved to handle more flexible situations.

2023-07-24 09:13 UTC, bioinformatist requested changes
Go go go!

2023-07-25 02:16 UTC, bioinformatist requested changes
Test code for `Inference` trait needs to be changed.

2023-07-25 02:16 UTC, bioinformatist commented on cml-tdengine/src/core/inference.rs
> +        let taos = cml.build_sync()?;
Why connection by blocking here?

2023-07-25 02:16 UTC, bioinformatist commented on cml-tdengine/src/core/inference.rs
> +        .await?;
We may need more than one batch running simultaneously to validate if async works well.

2023-07-25 02:16 UTC, bioinformatist commented on cml-tdengine/src/core/register.rs
> +        assert_eq!(4, records);
LGTM

2023-07-25 02:56 UTC, lazyky commented on cml-tdengine/src/core/inference.rs
> +        let taos = cml.build_sync()?;
That was my mistake

2023-07-25 14:05 UTC, bioinformatist requested changes
Almost done!

2023-07-25 14:05 UTC, bioinformatist commented on cml-tdengine/src/core/inference.rs
> +            }
There's no need for use a closure here, for the closure won't be used more than one time. Just move the calculations into loop, and use variables for staging intermediate results if necessary.

2023-07-26 01:43 UTC, bioinformatist approved these changes

2023-07-26 02:08 UTC, merged